### PR TITLE
refactored debian init script

### PR DESCRIPTION
**Pull request by arosenhagen**

### CODE REVIEW

**Comment by kgrubb** [comment]
Hey, This all looks good except for one little issue. The mailcatcher.upstart.conf.erb template uses the node['mailcatcher']['bin'] attribute as well. By changing that attribute to include /usr/bin/#{node['mailcatcher']['name']}, it would break the upstart script. Would you also be able to change that upstart script to include your new default['mailcatcher']['name'] attribute instead?

**Comment by arosenhagen** [comment]
fixed in last commit. I tried to get a systemd version for debian 8 but no luck so far. I also came into an issue, where the gem_package installs mailcatcher by default to /usr/local/bin - any hint how the bin path is determined by the gem?

**Comment by kgrubb** [comment]
I'm not sure to be honest. I would need to look at mailcatcher's source (Which i haven't looked at yet). I assume by default, mailcatcher would install to /usr/local/bin, since that is where non-system applications typically reside. I'll look into it.

**Comment by kgrubb** [comment]
_(2 months later...)_ Sorry for the long wait. I built a debian 7.8 vm today and ran `gem env`.
As you can see in my screenshot, it looks like the default executable directory for debian's rubygems setup is `/usr/local/bin`.
screen shot 2015-07-09 at 5 11 59 pm
It looks like this is the case for all other distros as well (I also checked on centos 7 and ubuntu 14.04). Because of this, I'm going to go ahead and change the default attribute to use /usr/local/bin. 

I prefer using /usr/local/bin anyway, since mailcatcher isn't a system application.

**Pull request merged**
